spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    url: jdbc:postgresql://100.119.72.89:5432/postgres
    user: postgres
    password: password
  r2dbc:
    password: password
    url: r2dbc:postgresql://100.119.72.89:5432/postgres
    username: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://100.119.72.89:5432/postgres
      password: password
      username: postgres
      driver-class-name: org.postgresql.Driver
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://100.119.72.89:6379"